Sprint2
Iker-elorrieta/RetoADPSP4 pull request #2
Opened 2021-01-14 06:18 UTC by Steff2020

Fin sprint 2

2021-01-15 12:28 UTC, Iker-elorrieta requested changes
1-. La base de datos no puede estar con datos. Solo se debe subir el esquema (Tablas y relaciones).
2-. Las pruebas se me quedan al 30%. Se crean elementos en la base datos. Pero muchas cosas no funcionan. Hay que automatizar las pruebas para que en cualquier equipo funcionen y lleguen al 80%.
3-. La aplicación cliente funciona correctamente pero no utiliza los datos creados por el servidor. ¿Hay forma de cargar los datos en el servidor sin ejecutar las pruebas? No encuentro la manera.
4-. No hay que subir al github ni los json ni los xml generados. Esas carpetas no se deberían subir ni poder descargar.
5-. Como recomendación, os vuelvo a comentar que los XML deberían ser creado sobre los elementos creados en la BD. Sin atributo no útiles para nuestra aplicación.
6-. Os he puesto algunos comentarios sobre la lectura de JSON.  No puede haber tantos for anidados, o por lo menos no de esa manera en el código.

2021-01-15 12:28 UTC, Iker-elorrieta commented on src/modelo/Json.java
> +				for(int y = 0 ; y < listaMunicipios.length ; y++)
¿Por que se recorren todos los municipios? Hay que hacer una query.

2021-01-15 12:28 UTC, Iker-elorrieta commented on src/modelo/Json.java
> +						for(int x = 0 ; x < nombres.length ;x++)
Hay muchos for anidados, no existen otra maneras?

2021-01-21 15:31 UTC, Steff2020 commented
Sprint 2 arreglado
falta las pruebas que lleguen al 80% de golpe

2021-01-21 19:15 UTC, merged